[manager]
show_hidden = true
show_ignored = true
sort_dir_first = true
# This ensures .dotfiles appear at the top.
sort_sensitive = false

[opener]
drawio = [
	{ run = 'flatpak run com.jgraph.drawio.desktop "$@"', orphan = true, for = 'linux' }
]

[open]
rules = [
	{ url = '*.drawio', use = 'drawio' },
	{ url = '*.dio', use = 'drawio' }
]

