foreground  #bfa6a0
background  #1a1b26
cursor      #f38ba8

# Custom shader file path is ~/.config/kitty/shaders/shader-0.slang
custom_shaders shader-0

#window_decorations full         # options: full, none
hide_window_decorations yes
initial_window_width 105
initial_window_height 35
window_padding_width 5
#window_padding_height 0
background_opacity 0.95
confirm_os_window_close 0

# Tab
tab_bar_stle powerline          # options: default, powerline, compact
tab_bar_edge top
hide_tab_bar_when_only_one_tab yes
active_tab_background #7aa2f7
active_tab_foreground #1a1b26
inactive_tab_background #1a1b26
inactive_tab_foreground #a9b1d6

# Keybindings
map ctrl+shift+t new_tab

# Cursor
cursor_shape beam
cursor_blink_interval 0.5

# Font
#font_family         Ubuntu Sans Mono
font_family          FiraCode Nerd Font
bold_font            FiraCode Nerd Font Bold
italic_font          FiraCode Nerd Font Italic
bold_italic_font     FiraCode Nerd Font Bold
font_size            13.0

# Scrollback
scrollback_lines 10000

# Performance
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Default shell: bash, zsh, nu, fish, ...
#shell sh -c "cat ascii-art.txt; exec sh"
shell sh -c "cat ascii-art.txt; exec zsh"
